feat: correct category buttons
hearchco/frontend pull request #139
Opened 2024-02-28 05:50 UTC by matijakljajic

2024-02-28 12:21 UTC, aleksasiriski requested changes
Great work! Please just fix the few little things mentioned and remove all unused imports.

2024-02-28 12:21 UTC, aleksasiriski commented on src/lib/components/Header.svelte
>  			<div class="w-0 md:w-16 md:ml-8" />
Move this to Searchbox inside if categories statement

2024-02-28 12:21 UTC, aleksasiriski commented on src/lib/components/Searchbox.svelte
> +	{#if categories == true}
No need for ==true

2024-02-28 12:21 UTC, aleksasiriski commented on src/lib/components/Searchbox.svelte
> +		{#if categories == true}
No need for ==true

2024-02-28 12:21 UTC, aleksasiriski commented on src/lib/functions/categoryFrom.ts
>  export function categoryFrom(query: string): string | undefined {
This never returns undefined now

2024-02-28 12:21 UTC, aleksasiriski commented on src/lib/functions/categoryFrom.ts
> +	let gottenCategory: string = 'general';
No need for : string since = '' already does that

2024-02-28 12:21 UTC, aleksasiriski commented on src/lib/functions/categoryFrom.ts
> +	let gottenCategory: string = 'general';
Maybe name it "categoryFromQuery" or "cat" (the latter is used in backend when reading from query)

2024-02-28 12:21 UTC, aleksasiriski commented on src/lib/components/Searchbox.svelte
> +	import { quadIn } from 'svelte/easing';
Unused import

2024-02-28 12:21 UTC, aleksasiriski commented on src/lib/components/Searchbox.svelte
> +	import { categoryEquals, categoryFrom, hasCategory } from '$lib/functions/categoryFrom';
categoryEquals unused import

2024-02-29 01:39 UTC, matijakljajic commented
@aleksasiriski todo: Rename currently named _Image_ category to _Images_.

2024-02-29 12:53 UTC, aleksasiriski approved these changes

2024-02-29 12:53 UTC, merged